version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "4173:4173"
    networks:
      - app-network

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  monitoring:
    build: 
      context: ./monitoring
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - client
      - server
      - monitoring
    networks:
      - app-network

networks:
  app-network:
