version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    networks:
      - app-network

  server:
    build: 
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - app-network

  monitoring:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - app-network
volumes:
  grafana_data:
networks:
  app-network:
