global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['server:8000']

  - job_name: 'client'
    static_configs:
      - targets: ['client:5173']
