global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # # Service Django/Gunicorn
  # - job_name: 'django-web'
  #   static_configs:
  #     - targets: ['localhost:8000']
  #   metrics_path: '/metrics'
  #   scrape_interval: 30s

  # # Service Nginx
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['localhost:80']
  #   metrics_path: '/metrics'
  #   scrape_interval: 30s
